### ISSUE TITLE
Can I skip mod version checking?

### ISSUE THREAD

**Issue by YuSheng133** [Dolly1016/Nebula#5]
Sorry for bothering. I'm a Among Us fan and Nebula On the Ship fan from China. 
In Chinese Among Us community, your mod has been liked by many people recently. Some translation worker in China was keen on making the translation text more and more funny. I'm one of these translators, but other player may use a normal translate by a serious sinicization group. If I add translations using your mod file, mod version checking may cause error to crash the game room. If using their translation, I may cause copyright issues. So I have a problem, can I skip mod version checking by deleting certain code?

Very sorry for interrupting you and thank you for bringing us quality mods. My English may not be very accurate, so I'm sorry in advance that I may not be able to communicate very smoothly.

P.S: sinicization group website link
https://amonguscn.club/%e6%98%9f%e4%ba%91%e8%88%b0%e6%a8%a1%e7%bb%84nebula-v1-16%e6%b1%89%e5%8c%96/

**Comment by Dolly1016** [comment]
Thank you for consulting.

NoS is updated now to add new option named "Don't Care Mismatched NoS" in the gear mark option.
Only host's option is affected.
