### ISSUE TITLE
プレイヤー追放に関する職業表示

### ISSUE THREAD

**Issue by xiaojinna** [Dolly1016/Nebula#6]
新バージョンにプレイヤー追放放送を追加することはできますか？
例：「プレイヤー名」は「職業名」

**Comment by Dolly1016** [comment]
ご要望をお寄せくださりありがとうございます。
そこほど難しくはありませんので、オプションで用意してみます。

**Comment by Dolly1016** [comment]
お待たせいたしました。
最新のSnapshot 23.01.05a にて追加いたしました。
Vanillaの設定「Confirm Ejects」をOnにした上で「Meeting Option」 -> 「Show Role Of Exiled」をOnにしていただくことでご利用いただけます。
