### ISSUE TITLE
关于许可证的问题（ライセンスに関する問題です）

### ISSUE THREAD

**Issue by Huier-Huang** [Dolly1016/Nebula#7]
我在您的Github仓库上似乎没找到开源许可证，我想询问下您的仓库使用的开源协议是什么？

（Githubリポジトリにオープンソースのライセンスが見つからないようですが、あなたのリポジトリで使用しているオープンソースのプロトコルは何ですか?）

**Comment by Dolly1016** [comment]
Thanks for your advice.
The license of this project follows GPLv3.

ご指摘くださりありがとうございます。ライセンスに関する記述を明記しました。
GPLv3に準拠しています。
